name: deploy

on:
  push:
    branches: [ "develop" ]

jobs:
  deploy: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Inject application.yml
      run: |
        mkdir -p ./src/main/resources && 
        echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml
    
    - name: install java 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'corretto'
        
    - name: assign grant gradlew
      run: chmod +x gradlew
    
    # Spring Boot 어플리케이션 Build (1)
    - name: Spring Boot Build
      run: ./gradlew clean build --exclude-task test

    # DockerHub Login (3)
    - name: docker login 
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    # Docker 이미지 Build (2)
    - name: docker image build
      run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/cns:latest .
    
    # Docker Hub push (4)
    - name: docker Hub push
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cns:latest

    # run application
    - name : run application via ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CNS_DEV_IP }}
        username: ${{ secrets.CNS_DEV_USERNAME }}
        key: ${{ secrets.CNS_DEV_SSH_KEY }}
        script: ${{ secrets.CNS_DEV_DEPLOY_COMMAND }}
